<a href="https://colab.research.google.com/github/liskibruh/EDA-on-Average-Temperatures-in-Cities-of-Pakistan/blob/main/clean_n_merge_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [364]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as matplotlib
import requests
from bs4 import BeautifulSoup as bs
import lxml

In [616]:
#reading data extracted from the url into dataframe
hecjournals=pd.read_csv("hecjournals.csv")
hecjournals_copy=hecjournals.copy()
hecjournals.head()

                        Journal name  ...                                                url
0                            Poetics  ...  https://hjrs.hec.gov.pk/index.php?r=site%2Fres...
1      English for Specific Purposes  ...  https://hjrs.hec.gov.pk/index.php?r=site%2Fres...
2                           Language  ...  https://hjrs.hec.gov.pk/index.php?r=site%2Fres...
3           Television and New Media  ...  https://hjrs.hec.gov.pk/index.php?r=site%2Fres...
4   Language Learning and Technology  ...  https://hjrs.hec.gov.pk/index.php?r=site%2Fres...

[5 rows x 13 columns]

In [670]:
#reading the dataset that was already given to us.. 
eprint=pd.read_csv("eprint_202112111250.csv")
eprint_copy=eprint.copy()
eprint

     eprintid  rev_number  ... gscholar_datestamp_minute  gscholar_datestamp_second
0           2           1  ...                       NaN                        NaN
1           4           6  ...                       NaN                        NaN
2          16           1  ...                       NaN                        NaN
3          17           1  ...                       NaN                        NaN
4          18           1  ...                       NaN                        NaN
..        ...         ...  ...                       ...                        ...
717      1774           1  ...                       NaN                        NaN
718      1775           1  ...                       NaN                        NaN
719      1776           1  ...                       NaN                        NaN
720      1788           5  ...                       NaN                        NaN
721      1789           5  ...                       NaN                        NaN

[722 rows x 92 columns]

# Cleaning Dataframes

In [367]:
print('Number of null values in eprint dataframe before cleaning: ', eprint.isnull().sum().sum())
print('Number of null values in hecjournals dataframe before cleaning: ', hecjournals.isnull().sum().sum())

Number of null values in eprint dataframe before cleaning:  42941
Number of null values in hecjournals dataframe before cleaning:  5055

In [368]:
eprint_clean=pd.DataFrame(eprint.dropna(how='all',thresh=600, axis=1)) #drop all columns that contain more than 600 null entries
hecjournals_clean=pd.DataFrame(hecjournals.dropna(how='all', thresh=3000, axis=1)) #drop all columns that contain more than 3000 null entries
print('Number of null values in eprint dataframe after cleaning: ', eprint_clean.isnull().sum().sum())
print('Number of null values in hecjournals dataframe after cleaning: ', hecjournals_clean.isnull().sum().sum())

Number of null values in eprint dataframe after cleaning:  381
Number of null values in hecjournals dataframe after cleaning:  0

In [369]:
eprint_clean.to_csv("eprint_202112111250_clean.csv")
hecjournals_clean.to_csv("hecjournals_clean.csv")

# Mapping

In [671]:
#s = eprint_copy.eprintid.replace(hecjournals['Journal name'])
hecjournals_copy.rename({'Journal name':'Title'}, axis=1, inplace=True)
s = hecjournals_copy.Title.replace(eprint_copy.set_index('eprintid')['title'])
s

0                                                 Poetics
1                           English for Specific Purposes
2                                                Language
3                                Television and New Media
4                        Language Learning and Technology
                              ...
5051        ARTCULTURA-REVISTA DE HISTORIA CULTURA E ARTE
5052     KWARTALNIK HISTORII ZYDOW-JEWISH HISTORY QUAR...
5053                                PENSAMIENTO Y CULTURA
5054        JOURNAL FOR THE STUDY OF PAUL AND HIS LETTERS
5055                Mujallah Tarikh wa Saqafat-i-Pakistan
Name: Title, Length: 5056, dtype: object

In [682]:
eprint_copy.rename({'eprintid': 'Journal_name'},axis=1, inplace=True)
eprint_copy['Journal_name']=s
eprint_copy[['Journal_name', 'title']]

                          Journal_name                                              title
0                              Poetics                                                NaN
1        English for Specific Purposes                                                NaN
2                             Language  Effectiveness of Manual Physical Therapy in Tr...
3             Television and New Media  Factors contributing anterior cruciate ligamen...
4     Language Learning and Technology  ROLE OF ROUTINE PHYSICAL THERAPY WITH AND WITH...
..                                 ...                                                ...
717                       Postmedieval  Energy-efficient clustering scheme for multiho...
718                 Philosophy Compass  Energy Efficient Clustering for Multihop Wirel...
719                     Israel Affairs  SNR maximization through relay selection in co...
720          Philosophy and Technology  Natural bioactive molecules: An alternative ap...
721        Journal of Heritage Tourism  Maternotoxicity and fetotoxicity in Rattus nor...

[722 rows x 2 columns]

In [683]:
hecjournals_copy['eprint_title']=s
hecjournals_copy[['eprint_title', 'title']]

                                           eprint_title                              title
0                                               Poetics                           Language
1                         English for Specific Purposes   Language Learning and Technology
2                                              Language               International Theory
3                              Television and New Media             Language and Education
4                      Language Learning and Technology               Modern Asian Studies
...                                                 ...                                ...
5051      ARTCULTURA-REVISTA DE HISTORIA CULTURA E ARTE                                NaN
5052   KWARTALNIK HISTORII ZYDOW-JEWISH HISTORY QUAR...                                NaN
5053                              PENSAMIENTO Y CULTURA                                NaN
5054      JOURNAL FOR THE STUDY OF PAUL AND HIS LETTERS                                NaN
5055              Mujallah Tarikh wa Saqafat-i-Pakistan                                NaN

[5056 rows x 2 columns]

# Merging

In [722]:
anyk=pd.DataFrame()
anyk['titles_all']=hecjournals_copy['eprint_title'].append(hecjournals_copy['title'].dropna())
anyk.index = pd.RangeIndex(len(anyk.index))
anyk

                                            titles_all
0                                              Poetics
1                        English for Specific Purposes
2                                             Language
3                             Television and New Media
4                     Language Learning and Technology
..                                                 ...
717                 History of Geo- and Space Sciences
718                          Studies in Travel Writing
719                         Journal of Semitic Studies
720   Journal of Immersion and Content-Based Langua...
721                          History of Economic Ideas

[5778 rows x 1 columns]

# Saving Resulting DataFrame in .csv File

In [723]:
anyk.to_csv('titles_final_dataset.csv')